//! Export the border as MAME artwork: a PNG with a transparent interior plus a layout that
//! stretches it over the whole view, so MAME draws the border inside its own frame and no
//! overlay has to fight a fullscreen window. Only right when the game's view fills the
//! screen (a 4:3 game on a 4:3 display): the tracker needs the border at the physical
//! screen edge.

use std::io::Write;
use std::path::Path;

use anyhow::{Context, Result};

use super::draw::{draw_border, Canvas, WHITE};

/// Write `<dir>/<name>/default.lay` and `<dir>/<name>/border.png` for a screen of `w` x `h`
/// pixels with a border `border_frac` of the shorter side thick.
pub fn export(dir: &Path, name: &str, w: u32, h: u32, border_frac: f64) -> Result<()> {
    let out = dir.join(name);
    std::fs::create_dir_all(&out).with_context(|| format!("creating {}", out.display()))?;
    let mut px = vec![0u32; w as usize * h as usize];
    let mut c = Canvas {
        px: &mut px,
        w: i64::from(w),
        h: i64::from(h),
    };
    draw_border(&mut c, w, h, border_frac);
    let rgba: Vec<[u8; 4]> = px
        .iter()
        .map(|&p| {
            if p == WHITE {
                [255, 255, 255, 255]
            } else {
                [0, 0, 0, 0]
            }
        })
        .collect();
    let png = encode_png(w, h, &rgba);
    std::fs::write(out.join("border.png"), png)?;
    // The element covers the same bounds as the screen, so the border lands on the view's
    // edge whatever the resolution; MAME scales the view to the window.
    let lay = format!(
        r#"<?xml version="1.0"?>
<!-- Generated by `sindenrs border export`: the coded border the driver tracks. -->
<mamelayout version="2">
	<element name="sinden_border">
		<image file="border.png" />
	</element>
	<view name="Sinden Border">
		<screen index="0">
			<bounds x="0" y="0" width="{w}" height="{h}" />
		</screen>
		<element ref="sinden_border">
			<bounds x="0" y="0" width="{w}" height="{h}" />
		</element>
	</view>
</mamelayout>
"#
    );
    std::fs::write(out.join("default.lay"), lay)?;
    Ok(())
}

/// A minimal PNG encoder: 8-bit RGBA, stored (uncompressed) deflate blocks. Dependency-free
/// and plenty for a mostly-empty image that is written once.
fn encode_png(w: u32, h: u32, rgba: &[[u8; 4]]) -> Vec<u8> {
    let mut raw = Vec::with_capacity((w as usize * 4 + 1) * h as usize);
    for row in rgba.chunks(w as usize) {
        raw.push(0); // filter: none
        for p in row {
            raw.extend_from_slice(p);
        }
    }
    let mut out = Vec::new();
    out.extend_from_slice(b"\x89PNG\r\n\x1a\n");
    let mut ihdr = Vec::new();
    ihdr.extend_from_slice(&w.to_be_bytes());
    ihdr.extend_from_slice(&h.to_be_bytes());
    ihdr.extend_from_slice(&[8, 6, 0, 0, 0]); // 8-bit RGBA
    chunk(&mut out, b"IHDR", &ihdr);
    chunk(&mut out, b"IDAT", &zlib_stored(&raw));
    chunk(&mut out, b"IEND", &[]);
    out
}

fn chunk(out: &mut Vec<u8>, kind: &[u8; 4], data: &[u8]) {
    let _ = out.write_all(&u32::try_from(data.len()).unwrap_or(u32::MAX).to_be_bytes());
    let mut crc = Crc32::new();
    crc.update(kind);
    crc.update(data);
    out.extend_from_slice(kind);
    out.extend_from_slice(data);
    out.extend_from_slice(&crc.finish().to_be_bytes());
}

fn zlib_stored(data: &[u8]) -> Vec<u8> {
    let mut out = vec![0x78, 0x01];
    let mut blocks = data.chunks(65535).peekable();
    if blocks.peek().is_none() {
        out.extend_from_slice(&[1, 0, 0, 0xFF, 0xFF]);
    }
    while let Some(b) = blocks.next() {
        let last = blocks.peek().is_none();
        let len = u16::try_from(b.len()).unwrap_or(u16::MAX);
        out.push(u8::from(last));
        out.extend_from_slice(&len.to_le_bytes());
        out.extend_from_slice(&(!len).to_le_bytes());
        out.extend_from_slice(b);
    }
    let (mut a, mut bsum) = (1u32, 0u32);
    for &x in data {
        a = (a + u32::from(x)) % 65521;
        bsum = (bsum + a) % 65521;
    }
    out.extend_from_slice(&((bsum << 16) | a).to_be_bytes());
    out
}

struct Crc32(u32);

impl Crc32 {
    fn new() -> Self {
        Self(0xFFFF_FFFF)
    }
    fn update(&mut self, data: &[u8]) {
        for &b in data {
            self.0 ^= u32::from(b);
            for _ in 0..8 {
                let mask = (!(self.0 & 1)).wrapping_add(1);
                self.0 = (self.0 >> 1) ^ (0xEDB8_8320 & mask);
            }
        }
    }
    fn finish(self) -> u32 {
        !self.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn crc_matches_reference() {
        let mut c = Crc32::new();
        c.update(b"123456789");
        assert_eq!(c.finish(), 0xCBF4_3926);
    }

    #[test]
    fn png_has_valid_structure() {
        let png = encode_png(2, 1, &[[255, 255, 255, 255], [0, 0, 0, 0]]);
        assert_eq!(&png[..8], b"\x89PNG\r\n\x1a\n");
        assert_eq!(&png[12..16], b"IHDR");
        assert_eq!(&png[16..20], &2u32.to_be_bytes());
        assert_eq!(&png[20..24], &1u32.to_be_bytes());
        // IHDR is 13 bytes: 8 sig + 4 len + 4 type + 13 data + 4 crc = 33, then IDAT.
        assert_eq!(&png[37..41], b"IDAT");
        assert_eq!(&png[png.len() - 8..png.len() - 4], b"IEND");
    }

    #[test]
    fn export_writes_layout_and_image() {
        let dir = std::env::temp_dir().join(format!("sindenrs-art-{}", std::process::id()));
        export(&dir, "sinden-border", 64, 48, 0.05).expect("export");
        let lay = std::fs::read_to_string(dir.join("sinden-border/default.lay")).expect("lay");
        assert!(lay.contains("border.png") && lay.contains("width=\"64\""));
        assert!(dir.join("sinden-border/border.png").exists());
        let _ = std::fs::remove_dir_all(dir);
    }
}
